#+TITLE: About me
#+SLUG: about
#+DATE: <2021-07-10>
#+AUTHOR: Luca Cambiaghi
#+OPTIONS: toc:nil num:nil
#+OPTIONS: ^:nil

My name is Luca, I am a Computer Scientist.
I grew up in northern Italy, orbiting around Milan.
In 2016 I moved to Copenhagen to achieve my MSc in Computer Science.

My favourite hobby is travelling.
After my graduation I spent 3 months backpacking across Chile, Bolivia, Peru and Colombia.
Another beautiful backpacking trip I have done was when visiting Nepal and India.

I also love reading and watching good movies and TV show.
The last book I read was 12 rules for life by Jordan Peterson.
The last TV show I (re)watched was Breaking Bad.

You can contact me by email at

#+HTML: <span style="cursor: pointer" onclick="this.textContent = ('luca.cambiaghi' + '@me' + String.fromCharCode(46) + 'com'); this.onclick = null; this.style.cursor='default'">(click.here.or.see.resume)</span>

** What I do
I am a Data Scientist, currently in between jobs.
My last employer was Maersk, a big Danish company which contributes to 30% of global trade with their container vessels.
I was working in the Demand Forecasting team, responsible for providing business users with hundreds of thousand of time series forecast every day.

We modelled customer demand from different angles, for example the number of empty containers imported and exported at each container pool.
Another example is how many containers would be ready to be loaded at each distinct terminal.

My next employer will be Boston Consulting Group.
In BCG Gamma, we solve the most challenging and impactful Data Science cases in a number of different industries.

I have experience in developing real world, scalable machine learning pipelines.
I am skilled in big data ingestion and cleaning, feature engineering, model development, deployment and monitoring.

Here you can see my full [[https://lucacambiaghi.com/static/resume.pdf][Resume]] .

** How I do it
I am most productive with Python.
On a day to day basis I work with ~numpy~, ~pandas~ and ~scikit-learn~.

During my first year as a FTE I added ~docker~ and ~kubernetes~ to my toolbox.

I am fascinated by ~clojure~ and functional programming.
My free time projects are often an attempt to learn some part of the ecosystem.
I look forward to the day I will be doing my data science work in ~clojure~.

